import type { Metadata } from "next";
import { Zen_Kurenaido } from "next/font/google";
import "./globals.css";

const zenKurenaido = Zen_Kurenaido({
  weight: "400",
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${zenKurenaido.className} antialiased bg-[var(--eeire_black)] text-[var(--ghost_white)]`}
      >
        {children}
      </body>
    </html>
  );
}
